name: CI-CD for iris ML model

on:
  push:
    branches:
      - main

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/setup-python@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrad pip
          pip install -r requirements.txt

      - name: Train model
        run: python ex1_train.python

      # - name: Run Flask server (test)
      # run:
      #   nohup python app.py &
        